version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  mysql:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=Astro119
      - POSTGRESQL_DATABASE=academy
      - POSTGRESQL_PORT_NUMBER=5432